measurement_navigator/vsf/apps/dashboard/sites/urls.py
from django.urls import path

from .views import ListDomains, ListSites, SiteDetailView, SitesEndpoint

app_name = "sites"

urlpatterns = [
    path("list_domains/", ListDomains.as_view(), name="list_domains"),
    path("list_sites/", ListSites.as_view(), name="list_sites"),
    path("sites/<int:id>/", SiteDetailView.as_view(), name="site_details"),
    path("sites/", SitesEndpoint.as_view(), name="sites"),
]

measurement_navigator/vsf/apps/dashboard/urls.py
from django.urls import include, path

from . import views

app_name = "dashboard"
urlpatterns = [
    # Auth
    path("login", views.VSFLogin.as_view(), name="login"),
    path("set_tz/", views.TZoneSelectorView.as_view(), name="set_tz"),
    path("", include("django.contrib.auth.urls")),
    # --------------- Sections --------------- #
    # -- Home
    path("", views.Dashboard.as_view(), name="home"),
    path("get_measurement", views.GetMeasurement.as_view(), name="get_measurement"),
    # -- Measurements
    path(
        "measurements/",
        include("apps.dashboard.measurements.urls", namespace="measurement"),
    ),
    # -- Submeasurements
    path(
        "submeasurements/",
        include(
            "apps.dashboard.measurements.submeasurements.urls",
            namespace="submeasurement",
        ),
    ),
    # -- Sites
    path("sites/", include("apps.dashboard.sites.urls", namespace="site")),
    # -- Event cases
    path("cases/", include("apps.dashboard.event_cases.urls", namespace="event_case")),
    # -- Events
    path("events/", include("apps.dashboard.events.urls", namespace="events")),
    # -- Control Panel
    path(
        "control_panel/",
        include("apps.dashboard.control_panel.urls", namespace="control_panel"),
    ),
    # -- Users
    path("users/", include("apps.dashboard.users.urls", namespace="users")),
    # -- Misc
    path("probes", views.ListProbes.as_view(), name="list_probes"),
]

measurement_navigator/vsf/apps/dashboard/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.UsersList.as_view(), name="users_list"),
    path("register/", views.UserCreateView.as_view(), name="users_create"),
    path("create/", views.UserCreateModalView.as_view(), name="users_register"),
    path("<int:pk>", views.UserUpdateView.as_view(), name="user_edit"),
    path(
        "passreveal/<int:pk>",
        views.CustomUserPasswdRevealView.as_view(),
        name="user_reveal_pass",
    ),
    path("activation/<int:pk>", views.CurtomUserActivationView, name="user_activation"),
    path(
        "createpass/<int:pk>",
        views.CustomUserCreatePass.as_view(),
        name="user_pass_create",
    ),
    path("profile/", views.UserProfileView.as_view(), name="user_profile"),
]

measurement_navigator/vsf/vsf/urls.py
# Django imports
import debug_toolbar
from django.contrib     import admin
from django.conf        import settings
from django.urls        import include, path, re_path
from django.conf.urls.static import static

# Third party imports
from rest_framework                 import routers
from drf_yasg                       import openapi
from rest_framework                 import permissions
from drf_yasg.views                 import get_schema_view
from rest_framework.documentation   import include_docs_urls

# Local imports
from .views import redirect_to_dashboard

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('dashboard/',      include('apps.dashboard.urls',         namespace = 'dashboard')),
    path('sites/',          include('apps.main.sites.urls',        namespace = 'sites')),
    path('api/',            include('apps.api.urls',               namespace = 'api')),
    path('measurements/',   include('apps.main.measurements.urls', namespace = 'measurements')),
    path('admin/',          admin.site.urls),
    path('', redirect_to_dashboard),
    path('prometheus/', include('django_prometheus.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

measurement_navigator/vsf/apps/dashboard/event_cases/forms.py
# Django imports
from django import forms

# Local imports
from apps.main.cases.models import Case


class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = "__all__"


class CaseCreateForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = [
            "title",
            "case_type",
            "start_date",
            "end_date",
            "category",
            "description",
        ]

measurement_navigator/vsf/apps/dashboard/events/forms.py
# Django imports
from django import forms

# Local imports
from apps.main.events.models import Event


class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields["identification"].disabled = True
        self.fields["issue_type"].disabled = True
        self.fields["domain"].disabled = True
        self.fields["asn"].disabled = True
        self.fields["end_date"].disabled = True

    class Meta:

        model = Event
        fields = [
            "identification",
            "confirmed",
            "end_date",
            "public_evidence",
            "private_evidence",
            "issue_type",
            "domain",
            "asn",
        ]
        widgets = {
            "public_evidence": forms.Textarea(attrs={"rows": 3}),
            "private_evidence": forms.Textarea(attrs={"rows": 3}),
        }

measurement_navigator/vsf/apps/dashboard/users/forms.py
from django import forms

from apps.main.users.models import CustomUser

ROLE_CHOICES = (
    ("1", "Superuser"),
    ("2", "Admin"),
    ("3", "Analist"),
    ("4", "Editor"),
    ("5", "Guest"),
)


class CustomUserForm(forms.ModelForm):
    role = forms.ChoiceField(choices=ROLE_CHOICES, required=True)

    class Meta:
        model = CustomUser
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "role",
        ]


class CustomUserPassForm(forms.ModelForm):
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = [
            "password1",
            "password2",
        ]

measurement_navigator/vsf/apps/dashboard/control_panel/views.py
# Django imports
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import JsonResponse
from django.http.response import HttpResponseBadRequest
# Permission imports
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.api.fp_tables_api.tasks import fp_update, measurement_update
# Local imports
from apps.main.measurements.submeasurements.tasks import \
    count_flags_submeasurements
from apps.main.users import decorators
from vsf.celery import USER_TASK_PRIORITY, transient_queue_name
from vsf.utils import ProcessState
# Inheritance imports
from vsf.views import VSFLoginRequiredMixin


@method_decorator([login_required, decorators.admin_required], name="dispatch")
class ControlPanel(VSFLoginRequiredMixin, TemplateView):
    """
    This view presents a set of buttons to run control
    functions over the database, such as request new data from
    ooni, count flags, reset flags, etc.

    Returned within context:
        - for each process named P, returns:
            + P : dict containing the following filds:
                    name : process name in our backend
                    state : its current state
                And the possible values of P:
                    + 'update_fastpath'
                    + 'measurement_recovery'
                    + 'count_flags'
                    + 'soft_flags'

        - states : a dict with every possible state string
                    + STARTING = "starting"
                    + RUNNING  = "running"
                    + IDLE     = "idle"
                    + FAILING  = "failing"
                    + FAILED   = "failed"
        - control_types : dict with every possible control type string:
                    + FASTPATH = 'fastpath' (trigger a fetch for new measurements in ooni)
                    + MEASUREMENT_RECOVERY = 'measurement_recovery' (trigger a fetch for the missing part of incomplete measurements)
                    + COUNT_FLAGS = 'count_flags' (trigger a flag counting process)
                    + UNKNOWN  = 'unknown'
            These are the only valid strings to be send in post request to request an action


    Also, you can perform POST requests to this view, these are the expected
    parameters:
        - control_type: type of control you want to trigger, the same values as passed
                        in the context through 'control_types' variable
        Depending on the control_type value, different values may be required:
        - 'fastpath' :
            + since : since date in 'YYYY-mm-dd' format
            + until : since date in 'YYYY-mm-dd' format
            + only_fastpath : string | none = if you want the results to come from the fastpath only.
        - 'measurement_recovery' : None, just try to recover every incomplete measurement
    The POST request will return a json data with some results:
            + result :
                        ok = The request has been succesfully processed and it is on its way
                    |   running = The request has been succesfully processed, but process was already running
    """

    template_name = "control_panel/control_panel.html"

    class CONTROL_TYPES:
        FASTPATH = "fastpath"
        MEASUREMENT_RECOVERY = "measurement_recovery"
        COUNT_FLAGS = "count_flags"
        UNKNOWN = "unknown"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update_fastpath"] = {
            "name": fp_update.vsf_name,
            "state": cache.get(fp_update.vsf_name),
        }
        context["measurement_recovery"] = {
            "name": measurement_update.vsf_name,
            "state": cache.get(measurement_update.vsf_name),
        }

        context["count_flags"] = {
            "name": count_flags_submeasurements.vsf_name,
            "state": cache.get(count_flags_submeasurements.vsf_name),
        }

        context["states"] = ProcessState.__dict__
        context["control_types"] = self.CONTROL_TYPES.__dict__
        return context

    def post(self, request, *args, **kwargs):
        """
        Return a result based on the following possible outcomes:
            result :=
                    ok : The process started to run succesfully
                |   already_running : didn't started the process since it was already running
        """
        # Define possible responses
        OK = "ok"
        RUNNING = "already_running"

        # Map from control panel options to function names
        process_names = {
            self.CONTROL_TYPES.FASTPATH: fp_update.vsf_name,  # vsf_name is a custom attribute that every vsf task should fill
            self.CONTROL_TYPES.MEASUREMENT_RECOVERY: measurement_update.vsf_name,
            self.CONTROL_TYPES.COUNT_FLAGS: count_flags_submeasurements.vsf_name,
        }

        # Get request data
        req = request.POST
        control = req.get("control_type")

        # Check the state; if process is not running and not failed, then it is busy right now,
        # try not to run it
        state = cache.get(
            process_names.get(control, self.CONTROL_TYPES.UNKNOWN), ProcessState.UNKNOWN
        )
        if (
            state != ProcessState.IDLE
            and state != ProcessState.FAILED
            and state != ProcessState.UNKNOWN
        ):
            return JsonResponse({"result": RUNNING})

        # Perform different actions depending on the control triggered
        # Fastpath update
        if control == ControlPanel.CONTROL_TYPES.FASTPATH:

            # Look since parameter
            since = req.get("since")
            if not since:
                # If since parameters is not provided, take "today at 00:00" as since
                since = datetime.now().strftime("%Y-%m-%d")

            # Look until parameter
            until = req.get("until")
            if not until:
                # if until parameter is not provided, take "today at midnight" as until
                until = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")

            # Get 'only_fastpath parameter', we just care if it is none or not
            only_fastpath = req.get("only_fastpath") is not None

            # run task
            fp_update.apply_async(
                kwargs={"until": until, "since": since, "only_fastpath": only_fastpath},
                queue=transient_queue_name,
                priority=USER_TASK_PRIORITY,
            )
            return JsonResponse({"result": OK})
        # Measurement recovery
        elif control == ControlPanel.CONTROL_TYPES.MEASUREMENT_RECOVERY:
            # Just run task
            measurement_update.apply_async(
                queue=transient_queue_name, priority=USER_TASK_PRIORITY
            )
            return JsonResponse({"result": OK})
        # Count flags
        elif control == ControlPanel.CONTROL_TYPES.COUNT_FLAGS:
            count_flags_submeasurements.apply_async(
                queue=transient_queue_name, priority=USER_TASK_PRIORITY
            )
            return JsonResponse({"result": OK})

        return JsonResponse({"result": OK})


def get_process_state(request):
    """
    Given a list of process names within a post request, return
    a dict with each process name related to its state
    This view will reject non-post requests. Expected arguments:
        + process : [str] = a list of process whose state you want to know, they should match
                            their corresponding vsf_name attribute

    returns:
        + process_stats : {process : status} = a dict that maps from process to their current status.
            Note that "process" is as specified in the request, and "status" could be one of the values
            specified in ProcessState in vsf.utils. If a process is actually unknown by the system,
            'ProcessStatus.UNKNOWN' will be returned for this process
    """
    if not request.POST:
        return HttpResponseBadRequest()

    req = request.POST
    process_list = list(req.getlist("process[]"))
    ans = {}
    for process in process_list:
        ans[process] = cache.get(process, ProcessState.UNKNOWN)
    return JsonResponse({"process_status": ans})

measurement_navigator/vsf/templates/dashboard/index.html
<!--
  ========================================
  MAIN LISTING MEASUREMENTS
  ========================================
 -->

{% extends 'extends/base.html' %}
{% load static %}
{% block custom_stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/DataTables/datatables.min.css' %}" /> 
{% endblock custom_stylesheet %} 

{% block tab_title %} VSF - Fastpath {% endblock tab_title %}
{% block title %} Fastpath {% endblock title %}
{% block sub_title %} List of all available measurements {% endblock sub_title %}

{% block route %}
<li class="breadcrumb-item">
  <a href="{% url home %}"><i class="feather icon-home"></i></a>
</li>
<li class="breadcrumb-item active">
  <a href="{% url home %}"><strong>Fastpath</strong></a>
</li>
{% endblock route %}

{% block content %}
<form id="urlForm">
  <nav class="navbar navbar-light bg-light rounded p-4">
    <div class="container-fluid">
      <div class="row">


        <div class="col-3 p-2">
          <input
            id="input"
            class="form-control mr-2 border-top-0 border-left-0 border-right-0 bg-transparent"
            type="search"
            placeholder="URL"
            aria-label="Search URL"
          />
        </div>


        <div class="col-3">
          <div class="row align-items-center rounded p-2">
            <div class="col-3 mx-auto">
              <label class='font-weight-bold'>
                Since
              </label>
            </div>
            <div class="col-9 mx-auto">
              <input id="since" class="text-secondary form-control mr-2" type="date" />
            </div>
          </div>            
        </div>


        <div class="col-3">
          <div class="row align-items-center rounded p-2 ml-1">
            <div class="col-3 mx-auto">
              <label class='font-weight-bold'>
                Until
              </label>
            </div>
            <div class="col-9 mx-auto">
              <input id="until" class="text-secondary form-control mr-2" type="date" />
            </div>
          </div>
        </div>


        <div class="col-3">
          <div class="row align-items-center rounded p-2 ml-1">
            <div class="col-3 mx-auto">
              <label class="font-weight-bold" for="asn">ASN</label>
            </div>
            <div class="col-9 mx-auto">
              <select class="custom-select" id="asn">
                <option selected value="">Any ASN</option>
                {% for asn in asns %}
                      <option value="{{ asn.asn }}" >{{ asn.asn }} - {{ asn.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </div>


        <div class="col-3 mt-3">
          <div class="row align-items-center rounded p-2">
            <div class="col-6 mx-auto">
              <label class="font-weight-bold" for="data-ready">Data Ready</label>
            </div>
            <div class="col-6 mx-auto">
              <select class="custom-select" id="data-ready">
                <option selected value="">Any</option>
                <option value="ready">Ready</option>
                <option value="not_ready">Not Ready</option>
                <option value="undetermined">Undetermined</option>
                <option value="dead">Dead</option>
              </select>
            </div>
          </div>
        </div>


        <div class="col-3 mt-3">
          <div class="row align-items-center rounded p-2">
            <div class="col-4 mx-auto">
              <label class="font-weight-bold" for="test-name">Test Type</label>
            </div>
            <div class="col-8 mx-auto">
              <select class="custom-select" id="test-name">
                <option selected value="">Choose Test Type</option>
                <option value="web_connectivity">Web Connectivity</option>
                <option value="http_requests">HTTP Requests</option>
                <option value="dns_consistency">DNS Consistency</option>
                <option value="http_invalid_request_line">
                  HTTP Invalid Request Line
                </option>
                <option value="bridge_reachability">Bridgr Reachability</option>
                <option value="http_header_field_manipulation">
                  HTTP Header Field Manipulation
                </option>
                <option value="multi_protocol_traceroute">
                  Multi Protocol Traceroute
                </option>
                <option value="meek_fronted_requests_test">
                  Meek Fronted Request Test
                </option>
                <option value="whatsapp">WhatsApp</option>
                <option value="facebook_messenger">Facebook Messenger</option>
                <option value="ndt">NTD</option>
                <option value="dash">Dash</option>
                <option value="telegram">Telegram</option>
                <option value="psiphon">Psiphon</option>
                <option value="tor">Tor</option>
                <option value="unknown">Unknown</option>
              </select>
            </div>
          </div>
        </div>


        <div class="col-3 mt-3">
          <div class="row align-items-center rounded p-2 ml-1">
            <div class="col-5 mx-auto">
              <label class="font-weight-bold" for="anomaly-state">Anomaly</label>
            </div>
            <div class="col-7 mx-auto">
              <select class="custom-select" id="anomaly-state">
                <option selected value="">Any</option>
                <option value="false">Anomaly False</option>
                <option value="true">Anomaly True</option>
              </select>
            </div>
          </div>
        </div>


        <div class="col-3 mt-3 p-2 pr-4">
          <button
            id="url-form-button"
            class="btn btn-blue float-right"
            type="submit"
          >
            <i class="fa fa-search"></i> <strong>Search</strong>
          </button>
        </div>
      </div>
    </div>
  </nav>
  <div class="card rounded p-3 mt-4">
    <table class="table table-striped mt-5" id="fastpath-table">
      <thead>
        <tr>
          <th class="text-center" scope="col">URL</th>
          <th class="text-center" scope="col">Data Ready</th>
          <th class="text-center" scope="col">Test Type</th>
          <th class="text-center" scope="col">Anomaly</th>
          <th class="text-center" scope="col">ASN</th>
          <th class="text-center" scope="col">Date</th>
          <th class="text-center" scope="col">Detailed Info</th>
        </tr>
      </thead>

      <tbody>
        {% for measurement in inbox_measurements %}
        <tr>
          <!-- INPUT -->
          <td>
            <div class='wrapper-dt'>
              {{ measurement.input }}
            </div>
          </td>

          <!-- STATE -->
          {% if measurement.data_ready == 'ready' %}
          <td class="text-center">
            <div class='wrapper-dt'><i class="far fa-check-circle text-success" title="Report Stored"></i></div>
          </td>
          {% elif measurement.data_ready == 'not_ready' %}
          <td class="text-center" title="Report Not Available Yet">
            <div class='wrapper-dt'><i class="fas fa-ban text-danger"></i></div>
          </td>
          {% elif measurement.data_ready == 'undetermined' %}
          <td class="text-center" title="Missing report">
            <div class='wrapper-dt'><i class="fas fa-exclamation-triangle text-warning"></i></div>
          </td>
          {% else %}
          <td class="text-center" title="Ignored Measurement" >
            <div class='wrapper-dt'><i class="fas fa-skull-crossbones text-disabled"></i></div>
          </td>
          {% endif %}

          <!-- TEST NAME -->
          <td class="text-center">{{ measurement.test_name }}</td>

          <!-- ANOMALY -->
          {% if measurement.anomaly %}
          <td class="text-center">
            <i class="fas fa-exclamation-circle text-warning"></i>
          </td>
          {% else %}
          <td class="text-center">N/A</td>
          {% endif %}

          <!-- ASN -->
          <td class="text-center">
            {{ measurement.probe_asn }}
          </td>

          <!-- TODO: necesitamos algún tipo de "mapeo" al nombre real -->

          <!-- DATE -->
          <td class="text-center">
            {{ measurement.measurement_start_time }}
          </td>

          <!-- MODAL BUTTON -->
          <td class="text-center">
            <!-- BUTTON TRIGGER MODAL -->
            <button
              id="{{ measurement.id }}"
              type="button"
              class="btn btn-blue detail-btn"
              data-toggle="modal"
              data-target="#modalCompleteInfo"
              aria-label="modalDetailedInfo"
            >
              Expand
            </button>
          </td>
        </tr>
        {% empty %}
        <td colspan="7" class="text-center">
          <div class="alert alert-danger" role="alert">
            No sites to show!
          </div>
        </td>
        {% endfor %}
      </tbody>
    </table>
  </div>
</form>

{% include "includes/fastpath-includes/detailed-info-modal.html" %}
{% endblock content %}

{% block custom_scripts %}
<script type="text/javascript" src="{% static 'plugins/DataTables/datatables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
<script>
  
  $('#fastpath-table').DataTable();

  let urlSearch;
  let data = {
    since   : "{{ search_params.since }}",
    until   : "{{ search_params.until }}",
    testName: "{{ search_params.testName }}",
    input   : "{{ search_params.input }}",
    asn     : "{{ search_params.asn }}",
    anomaly : "{{ search_params.anomaly }}",
    data_ready : "{{ search_params.data_ready }}"
  };

  let since    = data.since;
  let until    = data.until;
  let testName = data.testName;
  let input    = data.input;
  let asn      = data.asn;
  let anomaly  = data.anomaly;
  let data_ready = data.data_ready;

  (function () {
    $("#since").val(since);
    $("#until").val(until);
    $("#test-name").val(testName);
    $("#input").val(input);
    $("#asn").val(asn);
    $("#anomaly-state").val(anomaly);
  })();

  $("#urlForm").on("submit", function (event) {
    event.preventDefault();

    since    = $("#since").val();
    until    = $("#until").val();
    testName = $("#test-name").val();
    input    = $("#input").val();
    asn      = $("#asn").val();
    anomaly  = $("#anomaly-state").val();
    data_ready = $("#data-ready").val();

    urlSearch = "{% url home %}";

    data = {
      since   : since,
      until   : until,
      testName: testName,
      input   : input,
      asn     : asn,
      anomaly : anomaly,
      data_ready : data_ready
    };

    let url = urlSearch + "?" + $.param(data);

    window.location.href = url;
  });

  // Triggered when trying to retrieve data for a single measurement
  $('.detail-btn').on("click", function ( event ) {
    event.preventDefault();

    $.ajax({
      timeout: 300000,
      url    : "{% url 'dashboard:get_measurement' %}",
      type   : "GET",
      data   : { 'id': event.target.id },
      success: function (measurementJson) {
        $("#anomaly-detailed").text(measurementJson["anomaly"]);
        $("#scores-detailed").text(
          JSON.stringify(measurementJson["scores"], null, 2)
        );
        $("#tid-detailed").text(measurementJson["tid"]);
        $("#confirmed-detailed").text(measurementJson["confirmed"]);
        $("#failure-detailed").text(measurementJson["failure"]);
        $("#input-detailed").text(measurementJson["input"]);
        $("#catch-date-detailed").text(measurementJson["catch_date"]);
        $("#report-ready-detailed").text(measurementJson["report_ready"]);
        $("#report-id-detailed").text(measurementJson["report_id"]);
        $("#probe-asn-detailed").text(measurementJson["probe_asn"]);
        $("#probe-cc-detailed").text(measurementJson["probe_cc"]);
        $("#test-name-detailed").text(measurementJson["test_name"]);
        $("#measurement-url-detailed").text(measurementJson["measurement_url"]);
        $("#measurement-start-time-detailed").text(
          measurementJson["measurement_start_time"]
        );
      },
    });
  });
</script>
{% endblock custom_scripts %}