measurement_navigator/vsf/apps/dashboard/sites/urls.py
from django.urls import path

from .views import ListDomains, ListSites, SiteDetailView, SitesEndpoint

app_name = "sites"

urlpatterns = [
    path("list_domains/", ListDomains.as_view(), name="list_domains"),
    path("list_sites/", ListSites.as_view(), name="list_sites"),
    path("sites/<int:id>/", SiteDetailView.as_view(), name="site_details"),
    path("sites/", SitesEndpoint.as_view(), name="sites"),
]

measurement_navigator/vsf/apps/dashboard/urls.py
from django.urls import include, path

from . import views

app_name = "dashboard"
urlpatterns = [
    # Auth
    path("login", views.VSFLogin.as_view(), name="login"),
    path("set_tz/", views.TZoneSelectorView.as_view(), name="set_tz"),
    path("", include("django.contrib.auth.urls")),
    # --------------- Sections --------------- #
    # -- Home
    path("", views.Dashboard.as_view(), name="home"),
    path("get_measurement", views.GetMeasurement.as_view(), name="get_measurement"),
    # -- Measurements
    path(
        "measurements/",
        include("apps.dashboard.measurements.urls", namespace="measurement"),
    ),
    # -- Submeasurements
    path(
        "submeasurements/",
        include(
            "apps.dashboard.measurements.submeasurements.urls",
            namespace="submeasurement",
        ),
    ),
    # -- Sites
    path("sites/", include("apps.dashboard.sites.urls", namespace="site")),
    # -- Event cases
    path("cases/", include("apps.dashboard.event_cases.urls", namespace="event_case")),
    # -- Events
    path("events/", include("apps.dashboard.events.urls", namespace="events")),
    # -- Control Panel
    path(
        "control_panel/",
        include("apps.dashboard.control_panel.urls", namespace="control_panel"),
    ),
    # -- Users
    path("users/", include("apps.dashboard.users.urls", namespace="users")),
    # -- Misc
    path("probes", views.ListProbes.as_view(), name="list_probes"),
]

measurement_navigator/vsf/apps/dashboard/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.UsersList.as_view(), name="users_list"),
    path("register/", views.UserCreateView.as_view(), name="users_create"),
    path("create/", views.UserCreateModalView.as_view(), name="users_register"),
    path("<int:pk>", views.UserUpdateView.as_view(), name="user_edit"),
    path(
        "passreveal/<int:pk>",
        views.CustomUserPasswdRevealView.as_view(),
        name="user_reveal_pass",
    ),
    path("activation/<int:pk>", views.CurtomUserActivationView, name="user_activation"),
    path(
        "createpass/<int:pk>",
        views.CustomUserCreatePass.as_view(),
        name="user_pass_create",
    ),
    path("profile/", views.UserProfileView.as_view(), name="user_profile"),
]

measurement_navigator/vsf/vsf/urls.py
# Django imports
import debug_toolbar
from django.contrib     import admin
from django.conf        import settings
from django.urls        import include, path, re_path
from django.conf.urls.static import static

# Third party imports
from rest_framework                 import routers
from drf_yasg                       import openapi
from rest_framework                 import permissions
from drf_yasg.views                 import get_schema_view
from rest_framework.documentation   import include_docs_urls

# Local imports
from .views import redirect_to_dashboard

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('dashboard/',      include('apps.dashboard.urls',         namespace = 'dashboard')),
    path('sites/',          include('apps.main.sites.urls',        namespace = 'sites')),
    path('api/',            include('apps.api.urls',               namespace = 'api')),
    path('measurements/',   include('apps.main.measurements.urls', namespace = 'measurements')),
    path('admin/',          admin.site.urls),
    path('', redirect_to_dashboard),
    path('prometheus/', include('django_prometheus.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

measurement_navigator/vsf/apps/dashboard/event_cases/forms.py
# Django imports
from django import forms

# Local imports
from apps.main.cases.models import Case


class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = "__all__"


class CaseCreateForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = [
            "title",
            "case_type",
            "start_date",
            "end_date",
            "category",
            "description",
        ]

measurement_navigator/vsf/apps/dashboard/events/forms.py
# Django imports
from django import forms

# Local imports
from apps.main.events.models import Event


class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields["identification"].disabled = True
        self.fields["issue_type"].disabled = True
        self.fields["domain"].disabled = True
        self.fields["asn"].disabled = True
        self.fields["end_date"].disabled = True

    class Meta:

        model = Event
        fields = [
            "identification",
            "confirmed",
            "end_date",
            "public_evidence",
            "private_evidence",
            "issue_type",
            "domain",
            "asn",
        ]
        widgets = {
            "public_evidence": forms.Textarea(attrs={"rows": 3}),
            "private_evidence": forms.Textarea(attrs={"rows": 3}),
        }

measurement_navigator/vsf/apps/dashboard/users/forms.py
from django import forms

from apps.main.users.models import CustomUser

ROLE_CHOICES = (
    ("1", "Superuser"),
    ("2", "Admin"),
    ("3", "Analist"),
    ("4", "Editor"),
    ("5", "Guest"),
)


class CustomUserForm(forms.ModelForm):
    role = forms.ChoiceField(choices=ROLE_CHOICES, required=True)

    class Meta:
        model = CustomUser
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "role",
        ]


class CustomUserPassForm(forms.ModelForm):
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = [
            "password1",
            "password2",
        ]

measurement_navigator/vsf/apps/dashboard/control_panel/views.py
# Django imports
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import JsonResponse
from django.http.response import HttpResponseBadRequest
# Permission imports
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.api.fp_tables_api.tasks import fp_update, measurement_update
# Local imports
from apps.main.measurements.submeasurements.tasks import \
    count_flags_submeasurements
from apps.main.users import decorators
from vsf.celery import USER_TASK_PRIORITY, transient_queue_name
from vsf.utils import ProcessState
# Inheritance imports
from vsf.views import VSFLoginRequiredMixin


@method_decorator([login_required, decorators.admin_required], name="dispatch")
class ControlPanel(VSFLoginRequiredMixin, TemplateView):
    """
    This view presents a set of buttons to run control
    functions over the database, such as request new data from
    ooni, count flags, reset flags, etc.

    Returned within context:
        - for each process named P, returns:
            + P : dict containing the following filds:
                    name : process name in our backend
                    state : its current state
                And the possible values of P:
                    + 'update_fastpath'
                    + 'measurement_recovery'
                    + 'count_flags'
                    + 'soft_flags'

        - states : a dict with every possible state string
                    + STARTING = "starting"
                    + RUNNING  = "running"
                    + IDLE     = "idle"
                    + FAILING  = "failing"
                    + FAILED   = "failed"
        - control_types : dict with every possible control type string:
                    + FASTPATH = 'fastpath' (trigger a fetch for new measurements in ooni)
                    + MEASUREMENT_RECOVERY = 'measurement_recovery' (trigger a fetch for the missing part of incomplete measurements)
                    + COUNT_FLAGS = 'count_flags' (trigger a flag counting process)
                    + UNKNOWN  = 'unknown'
            These are the only valid strings to be send in post request to request an action


    Also, you can perform POST requests to this view, these are the expected
    parameters:
        - control_type: type of control you want to trigger, the same values as passed
                        in the context through 'control_types' variable
        Depending on the control_type value, different values may be required:
        - 'fastpath' :
            + since : since date in 'YYYY-mm-dd' format
            + until : since date in 'YYYY-mm-dd' format
            + only_fastpath : string | none = if you want the results to come from the fastpath only.
        - 'measurement_recovery' : None, just try to recover every incomplete measurement
    The POST request will return a json data with some results:
            + result :
                        ok = The request has been succesfully processed and it is on its way
                    |   running = The request has been succesfully processed, but process was already running
    """

    template_name = "control_panel/control_panel.html"

    class CONTROL_TYPES:
        FASTPATH = "fastpath"
        MEASUREMENT_RECOVERY = "measurement_recovery"
        COUNT_FLAGS = "count_flags"
        UNKNOWN = "unknown"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update_fastpath"] = {
            "name": fp_update.vsf_name,
            "state": cache.get(fp_update.vsf_name),
        }
        context["measurement_recovery"] = {
            "name": measurement_update.vsf_name,
            "state": cache.get(measurement_update.vsf_name),
        }

        context["count_flags"] = {
            "name": count_flags_submeasurements.vsf_name,
            "state": cache.get(count_flags_submeasurements.vsf_name),
        }

        context["states"] = ProcessState.__dict__
        context["control_types"] = self.CONTROL_TYPES.__dict__
        return context

    def post(self, request, *args, **kwargs):
        """
        Return a result based on the following possible outcomes:
            result :=
                    ok : The process started to run succesfully
                |   already_running : didn't started the process since it was already running
        """
        # Define possible responses
        OK = "ok"
        RUNNING = "already_running"

        # Map from control panel options to function names
        process_names = {
            self.CONTROL_TYPES.FASTPATH: fp_update.vsf_name,  # vsf_name is a custom attribute that every vsf task should fill
            self.CONTROL_TYPES.MEASUREMENT_RECOVERY: measurement_update.vsf_name,
            self.CONTROL_TYPES.COUNT_FLAGS: count_flags_submeasurements.vsf_name,
        }

        # Get request data
        req = request.POST
        control = req.get("control_type")

        # Check the state; if process is not running and not failed, then it is busy right now,
        # try not to run it
        state = cache.get(
            process_names.get(control, self.CONTROL_TYPES.UNKNOWN), ProcessState.UNKNOWN
        )
        if (
            state != ProcessState.IDLE
            and state != ProcessState.FAILED
            and state != ProcessState.UNKNOWN
        ):
            return JsonResponse({"result": RUNNING})

        # Perform different actions depending on the control triggered
        # Fastpath update
        if control == ControlPanel.CONTROL_TYPES.FASTPATH:

            # Look since parameter
            since = req.get("since")
            if not since:
                # If since parameters is not provided, take "today at 00:00" as since
                since = datetime.now().strftime("%Y-%m-%d")

            # Look until parameter
            until = req.get("until")
            if not until:
                # if until parameter is not provided, take "today at midnight" as until
                until = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")

            # Get 'only_fastpath parameter', we just care if it is none or not
            only_fastpath = req.get("only_fastpath") is not None

            # run task
            fp_update.apply_async(
                kwargs={"until": until, "since": since, "only_fastpath": only_fastpath},
                queue=transient_queue_name,
                priority=USER_TASK_PRIORITY,
            )
            return JsonResponse({"result": OK})
        # Measurement recovery
        elif control == ControlPanel.CONTROL_TYPES.MEASUREMENT_RECOVERY:
            # Just run task
            measurement_update.apply_async(
                queue=transient_queue_name, priority=USER_TASK_PRIORITY
            )
            return JsonResponse({"result": OK})
        # Count flags
        elif control == ControlPanel.CONTROL_TYPES.COUNT_FLAGS:
            count_flags_submeasurements.apply_async(
                queue=transient_queue_name, priority=USER_TASK_PRIORITY
            )
            return JsonResponse({"result": OK})

        return JsonResponse({"result": OK})


def get_process_state(request):
    """
    Given a list of process names within a post request, return
    a dict with each process name related to its state
    This view will reject non-post requests. Expected arguments:
        + process : [str] = a list of process whose state you want to know, they should match
                            their corresponding vsf_name attribute

    returns:
        + process_stats : {process : status} = a dict that maps from process to their current status.
            Note that "process" is as specified in the request, and "status" could be one of the values
            specified in ProcessState in vsf.utils. If a process is actually unknown by the system,
            'ProcessStatus.UNKNOWN' will be returned for this process
    """
    if not request.POST:
        return HttpResponseBadRequest()

    req = request.POST
    process_list = list(req.getlist("process[]"))
    ans = {}
    for process in process_list:
        ans[process] = cache.get(process, ProcessState.UNKNOWN)
    return JsonResponse({"process_status": ans})

measurement_navigator/vsf/templates/dashboard/extends/base.html
{% load static %}

{% with home='dashboard:home' logout='dashboard:logout' list_fastpath='dashboard:list_fastpath' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Favicon icon -->
    <link rel="icon" href="{% static 'img/vesinfiltro.png' %}" type="image/x-icon">

    <title>{% block tab_title %} VSF {% endblock tab_title %}</title>

    {% block style %}   
      <link href="{% static 'css/vendor.css' %}" rel="stylesheet" />
      <link href="{% static 'css/jquery.json-viewer.css' %}" rel="stylesheet" />
    {% endblock style %}
  
    {% block custom_stylesheet %}
    {% endblock custom_stylesheet %}
  </head>

  <body>


    <nav class="pcoded-navbar menu-light ">
      <div class="navbar-wrapper">
        <div class="navbar-content scroll-div" >

          <ul class="nav pcoded-inner-navbar pt-4">
            <li class="nav-item pcoded-menu-caption">
                <label>Main</label>
            </li>
            <li class="nav-item">
                <a href="{% url home %}" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="feather icon-home"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Home
                    </span>
                </a>
            </li>


            <li class="nav-item pcoded-menu-caption">
                <label>Incidents</label>
            </li>
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="fas fa-tachometer-alt"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Fastpath
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url home %}">All</a></li>
                </ul>
            </li>
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="fas fa-ruler"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Measurements
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url 'dashboard:measurement:list_measurements' %}">Measurements</a></li>
                    <li><a href="{% url 'dashboard:submeasurement:list_dns' %}">DNS</a></li>
                    <li><a href="{% url 'dashboard:submeasurement:list_http' %}">HTTP</a></li>
                    <li><a href="{% url 'dashboard:submeasurement:list_tcp' %}">TCP</a></li>
                    <li><a href="{% url 'dashboard:submeasurement:list_tor' %}">TOR</a></li>
                </ul>
            </li>
            
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="far fa-calendar"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Events
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url 'dashboard:events:all' %}">List Events</a></li>
                </ul>
            </li>
            
            
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="far fa-folder-open"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Cases
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url 'dashboard:event_cases:list_cases' %}">List Cases</a></li>
                    {% if user.is_editor %}
                    <li><a href="{% url 'dashboard:event_cases:create_case' %}">New Case</a></li>
                    {% endif %}
                </ul>
            </li>
            
            {% if user.is_analist %}
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="far fa-file"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Sites
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url 'dashboard:sites:list_domains' %}">Domains</a></li>
                    <li><a href="{% url 'dashboard:site:list_sites' %}">Sites</a></li>
                </ul>
            </li>
            {% endif %}
            {% if user.is_admin %}
            <li class="nav-item pcoded-menu-caption">
                <label>Settings</label>
            </li>
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="feather icon-briefcase"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Control Panel
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url 'dashboard:control_panel:controls' %}">Controls</a></li>
                </ul>
            </li>
            <li class="nav-item pcoded-hasmenu">
                <a href="#" class="nav-link ">
                    <span class="pcoded-micon">
                        <i class="feather icon-user"></i>
                    </span>
                    <span class="pcoded-mtext">
                        Users
                    </span>
                </a>
                <ul class="pcoded-submenu">
                    <li><a href="{% url 'dashboard:users:users_list' %}">List Users</a></li>
                    <li><a href="{% url 'dashboard:users:users_create' %}">New User</a></li>
                </ul>
            </li>
            {% endif %}
          </ul>
          
        </div>
      </div>
    </nav>

    <header class="navbar pcoded-header navbar-expand-lg navbar-light header-blue">	
      <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
        <a href="#!" class="b-brand">
        </a>
        <a href="{% url home %}" class="b-brand">
            <img height="30px" src="{% static 'img/logo.png' %}" alt="" class="logo">
        </a>
        <a href="#!" class="mob-toggler">
          <i class="feather icon-more-vertical"></i>
        </a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto mr-5">

          <li class="mr-5">
            <div class="dropdown drp-user">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="feather icon-user"></i> {{user.username}}
              </a>
              <div class="dropdown-menu dropdown-menu-right profile-notification">
                <ul class="pro-body">
                  <li>
                    <a href="{% url 'dashboard:users:user_profile' %}" class="dropdown-item">
                      <i class="feather icon-user"></i> Profile
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'admin:index' %}" class="dropdown-item">
                      <i class="feather icon-clipboard"></i> Admin Site
                    </a>
                  </li>
                  <li>
                    <a href="/dashboard/logout/" class="dropdown-item">
                      <i class="feather icon-log-out"></i> Logout
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </li>

          <li class=''>
              <div class="dropdown mr-5">
                  <select id="tz_selector" class="w-100 custom-select" name="tz_selector">
                      {% if request.session.system_tz == "1" %}
                          <option value="1" selected>UTC (0)</option>
                          <option value="2">Caracas (utc -4)</option>
                      {% else %}
                          <option value="1" >UTC (0)</option>
                          <option value="2" selected>Caracas (utc -4)</option>
                      {% endif %}
                  </select>
              </div>
          </li>

          
          
        </ul>
      </div>
    </header>


    <div class='float-right mr-5 pr-5'>
      {% block site_route %}
      <ul class="breadcrumb bg-dark mr-4">
        {% block route %}
        <li class="breadcrumb-item">
            <a href="{% url home %}" class="">
                <i class="feather icon-home"></i>
            </a>
        </li>
        <li class="breadcrumb-item active"><strong>Static Navigation</strong></li>
        {% endblock route %}
      </ul>
      {% endblock site_route %}
    </div>


    <div class="pcoded-main-container">
      <div class="pcoded-content">
          <div class="page-header">
              <div class="page-block">
                  <div class="row align-items-center">
                      <div class="col-md-12">
                          <div class="page-header-title">
                            <h5 class="m-b-10">{% block title %}Title{% endblock title %}</h5>
                            <small class="text-white sub_title">
                                {% block sub_title %}{% endblock sub_title %}
                            </small>
                          </div>

                      </div>
                  </div>
              </div>
          </div>
          <div class="row">
            {% block content %} {% endblock content %}
          </div>

      </div>
  </div>

  <div class="modal fade" id="confirmationTimezone" tabindex="-1" role="dialog" aria-labelledby="Confirmation Modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-danger" id="exampleModalLongTitle">Warning!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            Select a new timezone will refresh the current page.
            Seleccionar un nuevo huso horario refrescaría la página actual
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id='continueChangeTz'>Continue</button>
        </div>
      </div>
    </div>
  </div>

    {% block scripts %}
        <script src="{% static 'js/vendor-all.min.js' %}"></script>
        <script src="{% static 'js/plugins/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/plugins/sweetalert.js' %}"></script>
        <script src="{% static 'js/jquery.json-viewer.js' %}"></script>
        <script>


            $('#tz_selector').change(function(){
                console.log('SETEO', $('#tz_selector').val())
                jQuery.noConflict();
                $('#confirmationTimezone').modal('show');
                let data = {
                    tz: $('#tz_selector').val()
                };
            });
            
            $('#continueChangeTz').click(function() {
                let data = {
                    tz: $('#tz_selector').val()
                };
                $.ajax({
                    timeout: 300000,
                    url: "{% url 'dashboard:set_tz' %}",
                    contentType: "application/json; charset=utf-8",
                    type: "GET",
                    data: data,
                    success: function (metricsJson) {
                        console.log(metricsJson.system_tz)
                        location.reload();
                    }
                })
            })
        
        </script>

    {% endblock scripts %}
    {% block custom_scripts %}
        
    {% endblock custom_scripts %}
  </body>
</html>
{% endwith %}

measurement_navigator/vsf/templates/dashboard/extends/base_accounting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block tab_title %} Title {% endblock tab_title %}</title>

    <!-- Favicon icon -->
    <link rel="icon" href="{% static 'img/vesinfiltro.png' %}" type="image/x-icon">
    
    {% block style %}
      <link href="{% static 'css/vendor.css' %}" rel="stylesheet" />
    {% endblock style %}

    {% block custom_style %} {% endblock custom_style %}
  </head>
  <body>

    <div class="auth-wrapper">
      <div class="auth-content">
        <div class="card">
          <div class="row align-items-center text-center">
            <div class="col-md-12">
              <div class="card-body">
                <img height="30px" src="{% static 'img/logo-light.png' %}" alt="" class="mb-4">
                <h4 class="mb-3 f-w-400">
                  {% block title %} Title {% endblock title %}
                </h4>
                {% block body %} some form {% endblock body %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% block script %}
      <script src="{% static 'js/vendor-all.min.js' %}"></script>
      <script src="{% static 'js/plugins/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/pcoded.min.js' %}"></script>

    {% endblock script %}

    {% block custom_script %} {% endblock custom_script %}
  </body>
</html>